### PR TITLE
Develop about me#2

### PR DESCRIPTION
**Pull request by mvafatabar**
I am back Captain 👯 💃

### CODE REVIEW

**Comment by rayvafa** [comment]
The project failed as there are few lint issues. you can check lint issues by running `npm run lint`

**Comment by rayvafa** [comment]
also the page looks squashed:
screen shot 2016-11-17 at 11 39 48 pm

**Comment by mvafatabar** [comment]
would you please take a look again? i changed it a lil bit

**Comment by mvafatabar** [comment]
finally ! :)))

**Comment by rayvafa** [comment]
cool, fix the lint issues and let me know to have a look

**Pull request closed without merging**
